name: Update Documentation
on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:

permissions: write-all

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install -U -r requirements.txt
    - name: Compile documentation to HTML
      run: |
        sphinx-build -W -b html source build
    - name: Deploy to Pages
      uses: cloudflare/pages-action@1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        projectName: skykings-documentation
        directory: build
        branch: ${{ env.PAGES_BRANCH }}
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}
      env:
        PAGES_BRANCH: ${{ github.event_name == 'push' && github.ref_name ||  format('pr-{0}', github.event.number) }}
      if: github.event_name == 'push'
    - name: Comment on PR (Deploy Complete)
      uses: peter-evans/create-or-update-comment@v3
      with:
        body: |
          ## :rocket: Deployed to Cloudflare Pages!
          
          Commit ${{ github.sha }}.
      if: github.event_name == 'push'

